### ISSUE TITLE
请问 有相关评测数据集 开源的计划吗

### ISSUE THREAD

**Issue by zackdist** [CLUEbenchmark/SuperCLUE-Safety#1]
想要衡量自己微调之后模型对抗攻击能力是否有提升，请问有相关的开源计划或者可以用于测评的提交入口吗？

**Comment by MichaelCro** [comment]
同问

**Comment by brightmart** [comment]
请见文章最后部分的: https://github.com/CLUEbenchmark/SuperCLUE-Safety#%E8%AE%A8%E8%AE%BA%E4%BA%A4%E6%B5%81%E4%B8%8E%E4%BD%BF%E7%94%A8
